### ISSUE TITLE
Pointer dereference error when sending a NewRequestWithContext with a cancelled context

### ISSUE THREAD

**Issue by Minivera** [encoredev/go#1]
### What version of Go are you using (`go version`)?
Version in this repository

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/go/go1.16.3"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/go/go1.16.3/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/go/src/github.com/Minivera/headb/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3124819234=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I created a new request using `http.NewRequestWithContext` using a context that was already cancelled, when sending the request using `http.DefaultClient.Do(request)`, the code panics because of a pointer dereference somewhere in encore's version of go.

The dereference happens in the callstack from this function here: https://github.com/encoredev/go/blob/master/src/net/http/transport.go#L511 and is likely because a done context leads to `rr` being nil, set here: https://github.com/encoredev/go/blob/master/src/net/http/transport.go#L572. 

Here is a complete stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x729563]

goroutine 44 [running]:
encore.dev/runtime.httpCompleteRoundTrip(0xc0000beb00, 0x0, 0xa1f9e0, 0xc0001120b0)
	/home/user/.encore/runtime/runtime/http.go:177 +0x4c3
net/http.encoreFinishRoundTrip(0xc0000beb00, 0x0, 0xa1f9e0, 0xc0001120b0)
	/home/user/.encore/runtime/runtime/runtime.go:105 +0x49
net/http.(*Transport).roundTrip.func1(0xc00001d470, 0xc00001d478, 0xc00001d480)
	/home/user/.encore/encore-go/src/net/http/transport.go:511 +0x51
net/http.(*Transport).roundTrip(0xcd7e60, 0xc0000beb00, 0x0, 0xa1f9e0, 0xc0001120b0)
	/home/user/.encore/encore-go/src/net/http/transport.go:572 +0xd94
net/http.(*Transport).RoundTrip(0xcd7e60, 0xc0000beb00, 0xcd7e60, 0x0, 0x0)
	/home/user/.encore/encore-go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc0000beb00, 0xa20520, 0xcd7e60, 0x0, 0x0, 0x0, 0xc0000100c0, 0x4d5d9a, 0x1, 0x0)
	/home/user/.encore/encore-go/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0xcdf500, 0xc0000beb00, 0x0, 0x0, 0x0, 0xc0000100c0, 0x0, 0x1, 0xc0000beb00)
	/home/user/.encore/encore-go/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0xcdf500, 0xc0000beb00, 0x0, 0x0, 0x0)
	/home/user/.encore/encore-go/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
	/home/user/.encore/encore-go/src/net/http/client.go:585
encore.app/identity/github.GetUserInfo(0xa2b2b8, 0xc0000b0100, 0xc0000d6a80, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/go/src/github.com/Minivera/headb/identity/github/oauth.go:191 +0x3ee
encore.app/identity/github.HandleDeviceCodePolling(0xa2b2b8, 0xc0000b0100, 0xc0000de200, 0xc0000d6360, 0x28, 0xc000232230, 0x9, 0xc00023a080, 0x1f, 0x383, ...)
	/home/user/go/src/github.com/Minivera/headb/identity/github/oauth.go:251 +0x770
created by encore.app/identity.SignIn
	/home/user/go/src/github.com/Minivera/headb/identity/user.go:65 +0x55f
```

I think adding a check to make sure the request in `rr` is not nil for some reason could fix the issue, but I haven't dug into a potential fix that much.

**Comment by DomBlack** [comment]
Hi @Minivera,

Thank you for the bug report, this was fixed within our runtime components so should not be occurring anymore.
